name: "Re-trigger Workflows on open PRs"

on:
  push:

jobs:
  retrigger-workflows-on-open-prs:
    runs-on: ubuntu-latest

    steps:
      - uses: tiagobento/retrigger-workflow-on-open-prs@master
        with:
          github_token: ${{ secrets.RETRIGGER_CI_ON_OPEN_PRS_GITHUB_TOKEN }}
